# Generated by Django 5.0.6 on 2024-06-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='Gerente',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='direccion',
            field=models.TextField(default=''),
        ),
    ]
