# Generated by Django 5.0.6 on 2024-06-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursal', '0002_sucursal_gerente_sucursal_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='Cant_Trabajadores',
            field=models.TextField(),
        ),
    ]
