# Generated by Django 5.0.6 on 2024-06-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursal', '0003_alter_sucursal_cant_trabajadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='Cant_Trabajadores',
            field=models.TextField(default=''),
        ),
    ]
